
package GUI;

import DAO.ClientDAO;
import Metier.Client;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class PAjoutClient extends javax.swing.JPanel {

    JFrame f;
    Client c;
    int m;
    PAfficheClients p;
    public PAjoutClient(JFrame f, Client c,int m,PAfficheClients p) {
        this.f=f;
        this.c=c;
        this.m=m;
        this.p=p;
        initComponents();
        if(this.m == 2)
        {
            jLabel1.setText("Modifier un Client");
            jButtonValider.setText("Valider");
            TFNom.setText(c.getNom());
            TFPrenom.setText(c.getPrenom());
            TFCin.setText(c.getCin());
            TFPermis.setText(c.getPermi());
            TFTel.setText(c.getTel());
            if(c.getEmail() != null)
            {
                TFMail.setText(c.getEmail());
            }
            TFAdresse.setText(c.getCat());
            TFCathegorie.setSelectedItem(c.getCat());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFNom = new javax.swing.JTextField();
        TFPrenom = new javax.swing.JTextField();
        TFCin = new javax.swing.JTextField();
        TFPermis = new javax.swing.JTextField();
        TFTel = new javax.swing.JTextField();
        TFMail = new javax.swing.JTextField();
        TFAdresse = new javax.swing.JTextField();
        TFCathegorie = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setText("Nom");

        jLabel3.setText("Prénom");

        jLabel4.setText("CIN");

        jLabel5.setText("Permis");

        jLabel6.setText("Tel");

        jLabel7.setText("E-mail");

        jLabel8.setText("Adresse");

        jLabel9.setText("Catégorie");

        TFCathegorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Particulier", "Professionnel" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Ajoutez un client");

        jButtonValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick 1.png"))); // NOI18N
        jButtonValider.setText("Ajouter");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TFMail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFTel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFPermis, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFCin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFNom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFAdresse)
                            .addComponent(TFCathegorie, javax.swing.GroupLayout.Alignment.LEADING, 0, 163, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFPrenom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFCin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFPermis))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TFTel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TFMail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TFAdresse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TFCathegorie))
                .addGap(18, 18, 18)
                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        if(!(TFNom.getText().isEmpty() && TFPrenom.getText().isEmpty() &&
                TFCin.getText().isEmpty() && TFPermis.getText().isEmpty() && TFTel.getText().isEmpty()
                && TFAdresse.getText().isEmpty() && (TFCathegorie.getSelectedIndex() == -1)))
        {
            String nom = TFNom.getText();
            String prenom = TFPrenom.getText();
            String cin = TFCin.getText();
            String permis = TFPermis.getText();
            String adr = TFAdresse.getText();
            String tel = TFTel.getText();
            String cat = String.valueOf(TFCathegorie.getSelectedItem());
            Client c = new Client(cin, permis, nom, prenom, adr, tel, cat);
            if(!TFMail.getText().isEmpty())
            {
                c.setEmail(TFMail.getText());
            }
            if(this.m == 2)
            {
                if(ClientDAO.getInstance().edit(c))
                {
                    JOptionPane.showMessageDialog(this,"Client Modifie","Succes",JOptionPane.INFORMATION_MESSAGE);
                    this.p.tm.setData(this.p.tm.refresh());
                    this.f.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Erreur de connexion","Erreur",JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                if(ClientDAO.getInstance().insert(c))
                {
                    JOptionPane.showMessageDialog(this,"Client Ajoute","Succes",JOptionPane.INFORMATION_MESSAGE);
                    this.p.tm.setData(this.p.tm.refresh());
                    this.f.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Erreur de connexion","Erreur",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Erreur d'ajout","Erreur",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFAdresse;
    private javax.swing.JComboBox TFCathegorie;
    private javax.swing.JTextField TFCin;
    private javax.swing.JTextField TFMail;
    private javax.swing.JTextField TFNom;
    private javax.swing.JTextField TFPermis;
    private javax.swing.JTextField TFPrenom;
    private javax.swing.JTextField TFTel;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
